### ISSUE TITLE
New Issue I've Been Having

### ISSUE THREAD

**Issue by Ki11masler** [xuzhengyi1995/Manga_downloader#30]
This code has worked for me for the past three months but when I went to use it today I've been having this string of errors show up.
![Code Problem](https://user-images.githubusercontent.com/81728625/113239221-ecfd9900-926f-11eb-933e-c9e570195985.PNG)

I've only ever used code to set up and run this program so I'm sorry if I've missed an easy solution.

Using on bookwalker.jp

**Comment by xuzhengyi1995** [comment]
Hello,

This maybe caused by some network problem, maybe you could use a VPN and try it again.

Thank you!

**Comment by Ki11masler** [comment]
Thank you for the reply and great program 

Sorry but using a vpn i get the same result. 
![vpn code problem](https://user-images.githubusercontent.com/81728625/113351152-0f3ef780-9300-11eb-978b-f72d66ddb630.PNG)

**Comment by xuzhengyi1995** [comment]
Hello,

It's a little bit strange, I think normally this error is caused by slow page load or slow javascript.

You can use your browser and try to access bookwalker jp, see if it is really slow or not.

If it's a little bit slow, maybe you could try to set the time limit longer, here is the way to edit the program:

Add two new lines after [this line](https://github.com/xuzhengyi1995/Manga_downloader/blob/81c1ac1f8bce34d1a567800f24acd34914cd079b/downloader.py#L89)

**Notice**: There should be **8** espaces before the first character of the line

Two lines, you can copy it:

```python
        self.driver.set_page_load_timeout(600)
        self.driver.set_script_timeout(600)
```

Before:

```python
    def get_driver(self):
        option = webdriver.ChromeOptions()
        option.set_capability('unhandledPromptBehavior', 'accept')
        option.add_argument('high-dpi-support=1')
        option.add_argument('device-scale-factor=1')
        option.add_argument('force-device-scale-factor=1')
        option.add_argument(
            "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36")
        option.add_argument('window-size=%d,%d' % self.res)
        option.add_argument('headless')
        self.driver = webdriver.Chrome(chrome_options=option)
```

After:
```python
        self.driver = webdriver.Chrome(chrome_options=option)
        # This are the added lines
        self.driver.set_page_load_timeout(600)
        self.driver.set_script_timeout(600)
```

If it loaded normally, you could try to check your Chrome version, and make sure it can work with your Chrome driver, and you can just redownload it from [here](https://sites.google.com/a/chromium.org/chromedriver/downloads)

If the methods above do not work at all, please let me know, I will try it on my computer and you can also try to run it on another computer or try to use a Vitural Machine.

Thank you.

**Comment by Ki11masler** [comment]
Thank you for the suggestion. I tried running fresh code on an Ubuntu virtual machine and then I tried running the code with your suggested fix on the same virtual machine, these are the results. Included are my Chromium and Google Chrome version.
![vm code problems](https://user-images.githubusercontent.com/81728625/113391538-4ab9e000-9359-11eb-9df2-514cb0e48d15.PNG)
![VM edit code](https://user-images.githubusercontent.com/81728625/113391547-4c83a380-9359-11eb-9d5d-958014fa79a7.PNG)
![Chrome verstin](https://user-images.githubusercontent.com/81728625/113391553-4e4d6700-9359-11eb-8493-9fb9c7bbfb89.PNG)
Thank you for all the help

**Comment by xuzhengyi1995** [comment]
Hello,

According to [this reply](https://github.com/xuzhengyi1995/Manga_downloader/issues/32#issuecomment-812388802), I think yes maybe there is a compatibility problem of Chrome and ChromeDriver. I will also try it by myself and check out the reason.

Thank you!

**Comment by xuzhengyi1995** [comment]
I think it's very likely that this is the a compatibility problem, because Chrome has just release the version 89.0.4389.114 two days ago.

**Comment by Ki11masler** [comment]
this really brightness up my day thank you so vary much it is working great.
![working](https://user-images.githubusercontent.com/81728625/113463744-48a16100-93ed-11eb-98db-90aed6334cbe.PNG)
