### ISSUE TITLE
Problems with chromedriver? Bookwalker manga

### ISSUE THREAD

**Issue by oxidonitroso88** [xuzhengyi1995/Manga_downloader#34]
It worked fine 2 months ago... chrome updated to v89 and chromedriver  (v86) is not working...  (i tried updating the plugin to 89 version.  (making a substitution of chromedriver.exe the old for the new one) (now it, logins but stay on loading and never downloads) 

Tried to download the files again, (i was using an old version of the program)  but now it wont even login. It says this.... 
any ideas?

Traceback (most recent call last):
  File "C:\Manga_downloader-master\Manga_downloader-master\Manga_downloader-masterv89\main.py", line 5, in <module>
    from downloader import Downloader
  File "C:\Manga_downloader-master\Manga_downloader-master\Manga_downloader-masterv89\downloader.py", line 12, in <module>
    import undetected_chromedriver as uc
ModuleNotFoundError: No module named 'undetected_chromedriver'

**Comment by oxidonitroso88** [comment]
it seems i had to install undetected_chromedriver with pip.

it's working again.

I had another problem with chromedriver saying that the version i had was for 90 (when my chrome is v89) it was downloading automatically in users/(my user) i just put the v89 that i downloaded and worked just fine.

**Comment by xuzhengyi1995** [comment]
Yes I think now it's better to use a customized "undetected" chromedriver becuse BW has added some programe in the website to detect whether you are using a driver or not, you can check this issue: #32

And I am not sure it will work for a normal driver or not, I will check it later, but it's better to use a undetected driver because using the normal driver do have some methods to detect.
