### ISSUE TITLE
Questions on getting cookie from bookwalker TW

### ISSUE THREAD

**Issue by tassss2** [xuzhengyi1995/Manga_downloader#36]
The instruction suggests that "Find the first profile request, click it."

I am a bit confused since none of the files shows up after refreshing the network is named "profile", and I try to copy the cookie from other files ("e.g. the cookie listed in the members.js), I constantly receive the 998 error and the script cannot gets the number of pages when running the script.

[INFO](root) 2021-04-18 00:25:29 : Start download...
[ERROR](root) 2021-04-18 00:25:29 : Something wrong or download finished, Please check the error.png to see the web page.
Normally, you should logout and login, then renew the cookies to solve this problem.

May I know where can I exactly find the cookie to make the script works? Should I get it from the member page or manga URL webpage.Thanks.

And should I put the chromedriver file in the same folder of the script? Thanks.

**Comment by xuzhengyi1995** [comment]
Hello,

Sorry I think the `profile` is for the BW JP, for TW the first `/member` is ok, maybe not the `member.js`, just copy the cookie from the first request.

In fact, if you get an 998, I think you have found the right cookie, you can try to logout the account from all the devices and wait for about 20 to 30 minutes, then login on your computer and  **do not open any manga**, then copy the manga url and try again.

Because the BW will check if you have opened multiple browser at the same time and give you an error if you did.

Thank you.

**Comment by tassss2** [comment]
Thanks
